import type { PokemonStats } from "../features/run/types/game.types";
import {
  MEGA_EVOLUTIONS,
  ITEM_SPECIFIC_POKEMON,
  hasPokemonOfType,
  hasPokemonWithName,
  hasMegaEvolutionCandidate,
} from "./pokemonFilters";

export type ItemCategory =
  | "ball"
  | "heal"
  | "battle"
  | "evo"
  | "held"
  | "special"
  | "berry"
  | "tm"
  | "key";

export type ItemEffect =
  | { type: "heal_hp"; amount: number | "full" }
  | { type: "heal_status" }
  | { type: "revive"; hpPercent: number }
  | { type: "catch"; catchMultiplier: number }
  | {
      type: "evolve";
      targetPokemonId?: number;
      method?: "stone" | "trade" | "item";
    }
  | {
      type: "stat_boost";
      stat: keyof PokemonStats | "crit" | "acc" | "eva";
      amount: number;
    }
  | { type: "xp_boost"; multiplier: number }
  | { type: "mega_evo"; stoneId: string }
  | { type: "pp_restore"; amount: number | "full" }
  | { type: "friendship_boost" }
  | { type: "passive" }; // held items handled entirely in engine

export interface Item {
  id: string;
  name: string;
  spriteSlug: string;
  description: string;
  category: ItemCategory;
  effect: ItemEffect;
  buyable: boolean;
  shopPrice: number | null;
  condition?: (gameState: any) => boolean;
}

// ─────────────────────────────────────────────────────────────────────────────
// HOW TO ADD A NEW ITEM:
// 1. Find the PokeAPI slug: https://pokeapi.co/api/v2/item/[name]
//    or use resolveItemSlug("Item Name") from spriteRegistry.ts
// 2. Add the entry below with the correct spriteSlug
// 3. Set buyable: true/false to control shop availability
// 4. The sprite appears automatically via ItemSprite component
// ─────────────────────────────────────────────────────────────────────────────

export const ITEMS: Record<string, Item> = {
  // ── POKÉ BALLS ─────────────────────────────────────────────────────────────

  "poke-ball": {
    id: "poke-ball",
    name: "Poké Ball",
    spriteSlug: "poke-ball",
    description: "La Poké Ball estándar para capturar Pokémon.",
    category: "ball",
    effect: { type: "catch", catchMultiplier: 1.0 },
    buyable: true,
    shopPrice: 200,
  },
  "great-ball": {
    id: "great-ball",
    name: "Super Ball",
    spriteSlug: "great-ball",
    description: "Una buena Poké Ball con mayor tasa de captura.",
    category: "ball",
    effect: { type: "catch", catchMultiplier: 1.5 },
    buyable: true,
    shopPrice: 600,
    condition: (gs: any) => (gs.gymsBadges?.length || 0) >= 1,
  },
  "ultra-ball": {
    id: "ultra-ball",
    name: "Ultra Ball",
    spriteSlug: "ultra-ball",
    description: "Una Poké Ball excelente con alta tasa de captura.",
    category: "ball",
    effect: { type: "catch", catchMultiplier: 2.0 },
    buyable: true,
    shopPrice: 1200,
    condition: (gs: any) => (gs.gymsBadges?.length || 0) >= 3,
  },
  "master-ball": {
    id: "master-ball",
    name: "Master Ball",
    spriteSlug: "master-ball",
    description: "La Poké Ball definitiva. Captura sin fallar.",
    category: "ball",
    effect: { type: "catch", catchMultiplier: 255.0 },
    buyable: false,
    shopPrice: null,
  },
  "safari-ball": {
    id: "safari-ball",
    name: "Safari Ball",
    spriteSlug: "safari-ball",
    description: "Poké Ball especial usada en la Zona Safari.",
    category: "ball",
    effect: { type: "catch", catchMultiplier: 1.5 },
    buyable: false,
    shopPrice: null,
  },
  "net-ball": {
    id: "net-ball",
    name: "Red Ball",
    spriteSlug: "net-ball",
    description: "Más eficaz contra Pokémon de tipo Agua y Bicho (x3).",
    category: "ball",
    effect: { type: "catch", catchMultiplier: 3.0 },
    buyable: true,
    shopPrice: 1000,
    condition: (gs: any) => (gs.gymsBadges?.length || 0) >= 2,
  },
  "dive-ball": {
    id: "dive-ball",
    name: "Buceo Ball",
    spriteSlug: "dive-ball",
    description: "Más eficaz contra Pokémon encontrados bajo el agua (x3.5).",
    category: "ball",
    effect: { type: "catch", catchMultiplier: 3.5 },
    buyable: true,
    shopPrice: 1000,
    condition: (gs: any) => (gs.gymsBadges?.length || 0) >= 2,
  },
  "nest-ball": {
    id: "nest-ball",
    name: "Nido Ball",
    spriteSlug: "nest-ball",
    description: "Más eficaz cuanto más bajo sea el nivel del Pokémon.",
    category: "ball",
    effect: { type: "catch", catchMultiplier: 1.0 },
    buyable: true,
    shopPrice: 1000,
  },
  "repeat-ball": {
    id: "repeat-ball",
    name: "Repeat Ball",
    spriteSlug: "repeat-ball",
    description: "Más eficaz contra Pokémon que ya hayas capturado (x3.5).",
    category: "ball",
    effect: { type: "catch", catchMultiplier: 3.5 },
    buyable: true,
    shopPrice: 1000,
  },
  "timer-ball": {
    id: "timer-ball",
    name: "Crono Ball",
    spriteSlug: "timer-ball",
    description: "Más eficaz cuanto más turnos hayan pasado en combate.",
    category: "ball",
    effect: { type: "catch", catchMultiplier: 1.0 },
    buyable: true,
    shopPrice: 1000,
  },
  "luxury-ball": {
    id: "luxury-ball",
    name: "Lujo Ball",
    spriteSlug: "luxury-ball",
    description: "Aumenta rápidamente la amistad del Pokémon capturado.",
    category: "ball",
    effect: { type: "catch", catchMultiplier: 1.0 },
    buyable: true,
    shopPrice: 1000,
  },
  "premier-ball": {
    id: "premier-ball",
    name: "Premier Ball",
    spriteSlug: "premier-ball",
    description: "Una Poké Ball especial de edición limitada.",
    category: "ball",
    effect: { type: "catch", catchMultiplier: 1.0 },
    buyable: false,
    shopPrice: null,
  },
  "dusk-ball": {
    id: "dusk-ball",
    name: "Oscuridad Ball",
    spriteSlug: "dusk-ball",
    description: "Más eficaz de noche o en cuevas (x3.5).",
    category: "ball",
    effect: { type: "catch", catchMultiplier: 3.5 },
    buyable: true,
    shopPrice: 1000,
    condition: (gs: any) => (gs.gymsBadges?.length || 0) >= 2,
  },
  "heal-ball": {
    id: "heal-ball",
    name: "Cura Ball",
    spriteSlug: "heal-ball",
    description: "Recupera todos los PS del Pokémon capturado.",
    category: "ball",
    effect: { type: "catch", catchMultiplier: 1.0 },
    buyable: true,
    shopPrice: 300,
  },
  "quick-ball": {
    id: "quick-ball",
    name: "Quick Ball",
    spriteSlug: "quick-ball",
    description: "Muy eficaz si se usa al primer turno del combate (x5).",
    category: "ball",
    effect: { type: "catch", catchMultiplier: 5.0 },
    buyable: true,
    shopPrice: 1000,
  },
  "cherish-ball": {
    id: "cherish-ball",
    name: "Tesoro Ball",
    spriteSlug: "cherish-ball",
    description: "Ball especial para Pokémon distribuidos en eventos.",
    category: "ball",
    effect: { type: "catch", catchMultiplier: 1.0 },
    buyable: false,
    shopPrice: null,
  },
  "fast-ball": {
    id: "fast-ball",
    name: "Rapid Ball",
    spriteSlug: "fast-ball",
    description: "Más eficaz contra Pokémon con alta velocidad (x4).",
    category: "ball",
    effect: { type: "catch", catchMultiplier: 4.0 },
    buyable: false,
    shopPrice: null,
  },
  "level-ball": {
    id: "level-ball",
    name: "Nivel Ball",
    spriteSlug: "level-ball",
    description: "Más eficaz cuanto mayor sea la diferencia de nivel.",
    category: "ball",
    effect: { type: "catch", catchMultiplier: 1.0 },
    buyable: false,
    shopPrice: null,
  },
  "lure-ball": {
    id: "lure-ball",
    name: "Señuelo Ball",
    spriteSlug: "lure-ball",
    description: "Más eficaz contra Pokémon capturados con caña (x3).",
    category: "ball",
    effect: { type: "catch", catchMultiplier: 3.0 },
    buyable: false,
    shopPrice: null,
  },
  "heavy-ball": {
    id: "heavy-ball",
    name: "Peso Ball",
    spriteSlug: "heavy-ball",
    description: "Más eficaz contra Pokémon de gran peso.",
    category: "ball",
    effect: { type: "catch", catchMultiplier: 1.0 },
    buyable: false,
    shopPrice: null,
  },
  "love-ball": {
    id: "love-ball",
    name: "Amor Ball",
    spriteSlug: "love-ball",
    description: "Muy eficaz si el Pokémon rival es del sexo opuesto (x8).",
    category: "ball",
    effect: { type: "catch", catchMultiplier: 8.0 },
    buyable: false,
    shopPrice: null,
  },
  "friend-ball": {
    id: "friend-ball",
    name: "Amistad Ball",
    spriteSlug: "friend-ball",
    description: "El Pokémon capturado tiene alta amistad desde el inicio.",
    category: "ball",
    effect: { type: "catch", catchMultiplier: 1.0 },
    buyable: false,
    shopPrice: null,
  },
  "moon-ball": {
    id: "moon-ball",
    name: "Luna Ball",
    spriteSlug: "moon-ball",
    description:
      "Más eficaz contra Pokémon que evolucionan con Piedra Lunar (x4).",
    category: "ball",
    effect: { type: "catch", catchMultiplier: 4.0 },
    buyable: false,
    shopPrice: null,
  },
  "sport-ball": {
    id: "sport-ball",
    name: "Sport Ball",
    spriteSlug: "sport-ball",
    description: "Poké Ball especial para el Concurso de Bichos.",
    category: "ball",
    effect: { type: "catch", catchMultiplier: 1.5 },
    buyable: false,
    shopPrice: null,
  },
  "dream-ball": {
    id: "dream-ball",
    name: "Sueño Ball",
    spriteSlug: "dream-ball",
    description: "Muy eficaz contra Pokémon dormidos (x4).",
    category: "ball",
    effect: { type: "catch", catchMultiplier: 4.0 },
    buyable: false,
    shopPrice: null,
  },
  "beast-ball": {
    id: "beast-ball",
    name: "Ultra Ball",
    spriteSlug: "beast-ball",
    description: "Diseñada para capturar Ultraentes. Poco eficaz con otros.",
    category: "ball",
    effect: { type: "catch", catchMultiplier: 0.1 },
    buyable: false,
    shopPrice: null,
  },

  // ── MEDICINAS ──────────────────────────────────────────────────────────────

  potion: {
    id: "potion",
    name: "Poción",
    spriteSlug: "potion",
    description: "Restaura 20 PS.",
    category: "heal",
    effect: { type: "heal_hp", amount: 20 },
    buyable: true,
    shopPrice: 300,
  },
  "super-potion": {
    id: "super-potion",
    name: "Superpoción",
    spriteSlug: "super-potion",
    description: "Restaura 50 PS.",
    category: "heal",
    effect: { type: "heal_hp", amount: 50 },
    buyable: true,
    shopPrice: 700,
  },
  "hyper-potion": {
    id: "hyper-potion",
    name: "Hiperpoción",
    spriteSlug: "hyper-potion",
    description: "Restaura 200 PS.",
    category: "heal",
    effect: { type: "heal_hp", amount: 200 },
    buyable: true,
    shopPrice: 1200,
  },
  "max-potion": {
    id: "max-potion",
    name: "Poción Máxima",
    spriteSlug: "max-potion",
    description: "Restaura todos los PS.",
    category: "heal",
    effect: { type: "heal_hp", amount: "full" },
    buyable: true,
    shopPrice: 2500,
  },
  "full-restore": {
    id: "full-restore",
    name: "Restaurar Todo",
    spriteSlug: "full-restore",
    description: "Restaura todos los PS y cura problemas de estado.",
    category: "heal",
    effect: { type: "heal_hp", amount: "full" },
    buyable: true,
    shopPrice: 3000,
  },
  antidote: {
    id: "antidote",
    name: "Antídoto",
    spriteSlug: "antidote",
    description: "Cura el envenenamiento.",
    category: "heal",
    effect: { type: "heal_status" },
    buyable: true,
    shopPrice: 200,
  },
  awakening: {
    id: "awakening",
    name: "Despertar",
    spriteSlug: "awakening",
    description: "Despierta a un Pokémon dormido.",
    category: "heal",
    effect: { type: "heal_status" },
    buyable: true,
    shopPrice: 250,
  },
  "burn-heal": {
    id: "burn-heal",
    name: "Antiquemar",
    spriteSlug: "burn-heal",
    description: "Cura las quemaduras.",
    category: "heal",
    effect: { type: "heal_status" },
    buyable: true,
    shopPrice: 250,
  },
  "ice-heal": {
    id: "ice-heal",
    name: "Antihielo",
    spriteSlug: "ice-heal",
    description: "Descongela a un Pokémon congelado.",
    category: "heal",
    effect: { type: "heal_status" },
    buyable: true,
    shopPrice: 250,
  },
  "paralyze-heal": {
    id: "paralyze-heal",
    name: "Antiparalizador",
    spriteSlug: "paralyze-heal",
    description: "Cura la parálisis.",
    category: "heal",
    effect: { type: "heal_status" },
    buyable: true,
    shopPrice: 200,
  },
  "full-heal": {
    id: "full-heal",
    name: "Cura Total",
    spriteSlug: "full-heal",
    description: "Cura cualquier problema de estado.",
    category: "heal",
    effect: { type: "heal_status" },
    buyable: true,
    shopPrice: 600,
  },
  revive: {
    id: "revive",
    name: "Revivir",
    spriteSlug: "revive",
    description: "Revive a un Pokémon debilitado con 50% de sus PS.",
    category: "heal",
    effect: { type: "revive", hpPercent: 0.5 },
    buyable: true,
    shopPrice: 1500,
  },
  "max-revive": {
    id: "max-revive",
    name: "Max. Revivir",
    spriteSlug: "max-revive",
    description: "Revive a un Pokémon debilitado con todos sus PS.",
    category: "heal",
    effect: { type: "revive", hpPercent: 1.0 },
    buyable: false,
    shopPrice: null,
  },
  "sacred-ash": {
    id: "sacred-ash",
    name: "Ceniza Sagrada",
    spriteSlug: "sacred-ash",
    description: "Revive a todos los Pokémon debilitados con todos sus PS.",
    category: "heal",
    effect: { type: "revive", hpPercent: 1.0 },
    buyable: false,
    shopPrice: null,
  },
  "berry-juice": {
    id: "berry-juice",
    name: "Zumo de Baya",
    spriteSlug: "berry-juice",
    description: "Restaura 20 PS.",
    category: "heal",
    effect: { type: "heal_hp", amount: 20 },
    buyable: false,
    shopPrice: null,
  },
  "fresh-water": {
    id: "fresh-water",
    name: "Agua Fresca",
    spriteSlug: "fresh-water",
    description: "Restaura 30 PS.",
    category: "heal",
    effect: { type: "heal_hp", amount: 30 },
    buyable: true,
    shopPrice: 200,
  },
  "soda-pop": {
    id: "soda-pop",
    name: "Refresco",
    spriteSlug: "soda-pop",
    description: "Restaura 50 PS.",
    category: "heal",
    effect: { type: "heal_hp", amount: 50 },
    buyable: true,
    shopPrice: 300,
  },
  lemonade: {
    id: "lemonade",
    name: "Limonada",
    spriteSlug: "lemonade",
    description: "Restaura 80 PS.",
    category: "heal",
    effect: { type: "heal_hp", amount: 80 },
    buyable: true,
    shopPrice: 350,
  },
  "moomoo-milk": {
    id: "moomoo-milk",
    name: "Leche MuMu",
    spriteSlug: "moomoo-milk",
    description: "Restaura 100 PS.",
    category: "heal",
    effect: { type: "heal_hp", amount: 100 },
    buyable: true,
    shopPrice: 500,
  },
  "energy-powder": {
    id: "energy-powder",
    name: "Polvo Vigor",
    spriteSlug: "energy-powder",
    description: "Restaura 60 PS pero baja la amistad.",
    category: "heal",
    effect: { type: "heal_hp", amount: 60 },
    buyable: true,
    shopPrice: 500,
  },
  "energy-root": {
    id: "energy-root",
    name: "Raíz Vigor",
    spriteSlug: "energy-root",
    description: "Restaura 120 PS pero baja la amistad.",
    category: "heal",
    effect: { type: "heal_hp", amount: 120 },
    buyable: true,
    shopPrice: 800,
  },
  "heal-powder": {
    id: "heal-powder",
    name: "Polvo Cura",
    spriteSlug: "heal-powder",
    description: "Cura problemas de estado pero baja la amistad.",
    category: "heal",
    effect: { type: "heal_status" },
    buyable: true,
    shopPrice: 450,
  },
  "revival-herb": {
    id: "revival-herb",
    name: "Hierba Revivir",
    spriteSlug: "revival-herb",
    description: "Revive con todos los PS pero baja mucho la amistad.",
    category: "heal",
    effect: { type: "revive", hpPercent: 1.0 },
    buyable: true,
    shopPrice: 2800,
  },
  ether: {
    id: "ether",
    name: "Éter",
    spriteSlug: "ether",
    description: "Restaura 10 PP de un movimiento.",
    category: "heal",
    effect: { type: "pp_restore", amount: 10 },
    buyable: false,
    shopPrice: null,
  },
  "max-ether": {
    id: "max-ether",
    name: "Éter Máximo",
    spriteSlug: "max-ether",
    description: "Restaura todos los PP de un movimiento.",
    category: "heal",
    effect: { type: "pp_restore", amount: "full" },
    buyable: false,
    shopPrice: null,
  },
  elixir: {
    id: "elixir",
    name: "Elixir",
    spriteSlug: "elixir",
    description: "Restaura 10 PP de todos los movimientos.",
    category: "heal",
    effect: { type: "pp_restore", amount: 10 },
    buyable: false,
    shopPrice: null,
  },
  "max-elixir": {
    id: "max-elixir",
    name: "Elixir Máximo",
    spriteSlug: "max-elixir",
    description: "Restaura todos los PP de todos los movimientos.",
    category: "heal",
    effect: { type: "pp_restore", amount: "full" },
    buyable: false,
    shopPrice: null,
  },
  "pp-up": {
    id: "pp-up",
    name: "PP Más",
    spriteSlug: "pp-up",
    description: "Sube los PP máximos de un movimiento en 1/5.",
    category: "special",
    effect: { type: "passive" },
    buyable: false,
    shopPrice: null,
  },
  "rare-candy": {
    id: "rare-candy",
    name: "Carameloraro",
    spriteSlug: "rarecandy",
    description: "Sube el nivel del Pokémon en 1.",
    category: "special",
    effect: { type: "passive" },
    buyable: false,
    shopPrice: null,
  },
  "pp-max": {
    id: "pp-max",
    name: "PP Máximo",
    spriteSlug: "pp-max",
    description: "Sube los PP máximos de un movimiento al máximo.",
    category: "special",
    effect: { type: "passive" },
    buyable: false,
    shopPrice: null,
  },

  // ── VITAMINAS (STAT BOOSTERS PERMANENTES) ─────────────────────────────────

  "hp-up": {
    id: "hp-up",
    name: "Salud Más",
    spriteSlug: "hp-up",
    description: "Sube los PS base del Pokémon.",
    category: "special",
    effect: { type: "stat_boost", stat: "hp", amount: 10 },
    buyable: true,
    shopPrice: 9800,
  },
  protein: {
    id: "protein",
    name: "Proteína",
    spriteSlug: "protein",
    description: "Sube el Ataque base del Pokémon.",
    category: "special",
    effect: { type: "stat_boost", stat: "attack", amount: 10 },
    buyable: true,
    shopPrice: 9800,
  },
  iron: {
    id: "iron",
    name: "Hierro",
    spriteSlug: "iron",
    description: "Sube la Defensa base del Pokémon.",
    category: "special",
    effect: { type: "stat_boost", stat: "defense", amount: 10 },
    buyable: true,
    shopPrice: 9800,
  },
  calcium: {
    id: "calcium",
    name: "Calcio",
    spriteSlug: "calcium",
    description: "Sube el Ataque Especial base del Pokémon.",
    category: "special",
    effect: { type: "stat_boost", stat: "spAtk", amount: 10 },
    buyable: true,
    shopPrice: 9800,
  },
  zinc: {
    id: "zinc",
    name: "Zinc",
    spriteSlug: "zinc",
    description: "Sube la Defensa Especial base del Pokémon.",
    category: "special",
    effect: { type: "stat_boost", stat: "spDef", amount: 10 },
    buyable: true,
    shopPrice: 9800,
  },
  carbos: {
    id: "carbos",
    name: "Carburo",
    spriteSlug: "carbos",
    description: "Sube la Velocidad base del Pokémon.",
    category: "special",
    effect: { type: "stat_boost", stat: "speed", amount: 10 },
    buyable: true,
    shopPrice: 9800,
  },

  // ── OBJETOS DE BATALLA (X ITEMS) ───────────────────────────────────────────

  "x-attack": {
    id: "x-attack",
    name: "Ataque X",
    spriteSlug: "x-attack",
    description: "Sube el Ataque en combate.",
    category: "battle",
    effect: { type: "stat_boost", stat: "attack", amount: 1 },
    buyable: true,
    shopPrice: 500,
  },
  "x-defense": {
    id: "x-defense",
    name: "Defensa X",
    spriteSlug: "x-defense",
    description: "Sube la Defensa en combate.",
    category: "battle",
    effect: { type: "stat_boost", stat: "defense", amount: 1 },
    buyable: true,
    shopPrice: 550,
  },
  "x-sp-atk": {
    id: "x-sp-atk",
    name: "Ataque Esp. X",
    spriteSlug: "x-sp-atk",
    description: "Sube el Ataque Especial en combate.",
    category: "battle",
    effect: { type: "stat_boost", stat: "spAtk", amount: 1 },
    buyable: true,
    shopPrice: 350,
  },
  "x-sp-def": {
    id: "x-sp-def",
    name: "Defensa Esp. X",
    spriteSlug: "x-sp-def",
    description: "Sube la Defensa Especial en combate.",
    category: "battle",
    effect: { type: "stat_boost", stat: "spDef", amount: 1 },
    buyable: true,
    shopPrice: 350,
  },
  "x-speed": {
    id: "x-speed",
    name: "Velocidad X",
    spriteSlug: "x-speed",
    description: "Sube la Velocidad en combate.",
    category: "battle",
    effect: { type: "stat_boost", stat: "speed", amount: 1 },
    buyable: true,
    shopPrice: 350,
  },
  "x-accuracy": {
    id: "x-accuracy",
    name: "Precisión X",
    spriteSlug: "x-accuracy",
    description: "Sube la Precisión en combate.",
    category: "battle",
    effect: { type: "stat_boost", stat: "acc", amount: 1 },
    buyable: true,
    shopPrice: 950,
  },
  "dire-hit": {
    id: "dire-hit",
    name: "Golpe Certero",
    spriteSlug: "dire-hit",
    description: "Aumenta la probabilidad de golpe crítico en combate.",
    category: "battle",
    effect: { type: "stat_boost", stat: "crit", amount: 1 },
    buyable: true,
    shopPrice: 650,
  },
  "guard-spec": {
    id: "guard-spec",
    name: "Guardaspec",
    spriteSlug: "guard-spec",
    description:
      "Evita que bajen las estadísticas del equipo durante 5 turnos.",
    category: "battle",
    effect: { type: "passive" },
    buyable: true,
    shopPrice: 700,
  },

  // ── PIEDRAS EVOLUTIVAS ─────────────────────────────────────────────────────

  "fire-stone": {
    id: "fire-stone",
    name: "Piedra Fuego",
    spriteSlug: "fire-stone",
    description: "Evoluciona a ciertos Pokémon de tipo Fuego.",
    category: "evo",
    effect: { type: "evolve", method: "stone" },
    buyable: true,
    shopPrice: 2100,
  },
  "water-stone": {
    id: "water-stone",
    name: "Piedra Agua",
    spriteSlug: "water-stone",
    description: "Evoluciona a ciertos Pokémon de tipo Agua.",
    category: "evo",
    effect: { type: "evolve", method: "stone" },
    buyable: true,
    shopPrice: 2100,
  },
  "thunder-stone": {
    id: "thunder-stone",
    name: "Piedra Trueno",
    spriteSlug: "thunder-stone",
    description: "Evoluciona a ciertos Pokémon de tipo Eléctrico.",
    category: "evo",
    effect: { type: "evolve", method: "stone" },
    buyable: true,
    shopPrice: 2100,
  },
  "leaf-stone": {
    id: "leaf-stone",
    name: "Piedra Hoja",
    spriteSlug: "leaf-stone",
    description: "Evoluciona a ciertos Pokémon de tipo Planta.",
    category: "evo",
    effect: { type: "evolve", method: "stone" },
    buyable: true,
    shopPrice: 2100,
  },
  "moon-stone": {
    id: "moon-stone",
    name: "Piedra Lunar",
    spriteSlug: "moon-stone",
    description: "Evoluciona a ciertos Pokémon.",
    category: "evo",
    effect: { type: "evolve", method: "stone" },
    buyable: true,
    shopPrice: 2100,
  },
  "sun-stone": {
    id: "sun-stone",
    name: "Piedra Solar",
    spriteSlug: "sun-stone",
    description: "Evoluciona a ciertos Pokémon.",
    category: "evo",
    effect: { type: "evolve", method: "stone" },
    buyable: true,
    shopPrice: 2100,
  },
  "shiny-stone": {
    id: "shiny-stone",
    name: "Piedra Brillante",
    spriteSlug: "shiny-stone",
    description: "Evoluciona a ciertos Pokémon.",
    category: "evo",
    effect: { type: "evolve", method: "stone" },
    buyable: false,
    shopPrice: null,
  },
  "dusk-stone": {
    id: "dusk-stone",
    name: "Piedra Sombría",
    spriteSlug: "dusk-stone",
    description: "Evoluciona a ciertos Pokémon de tipo Siniestro y Fantasma.",
    category: "evo",
    effect: { type: "evolve", method: "stone" },
    buyable: false,
    shopPrice: null,
  },
  "dawn-stone": {
    id: "dawn-stone",
    name: "Piedra Aurora",
    spriteSlug: "dawn-stone",
    description: "Evoluciona a ciertos Pokémon según su género.",
    category: "evo",
    effect: { type: "evolve", method: "stone" },
    buyable: false,
    shopPrice: null,
  },
  "ice-stone": {
    id: "ice-stone",
    name: "Piedra Hielo",
    spriteSlug: "ice-stone",
    description: "Evoluciona a ciertos Pokémon de tipo Hielo.",
    category: "evo",
    effect: { type: "evolve", method: "stone" },
    buyable: false,
    shopPrice: null,
  },
  "oval-stone": {
    id: "oval-stone",
    name: "Piedra Oval",
    spriteSlug: "oval-stone",
    description: "Evoluciona a Happiny cuando sube de nivel de día.",
    category: "evo",
    effect: { type: "evolve", method: "stone" },
    buyable: false,
    shopPrice: null,
  },
  "kings-rock": {
    id: "kings-rock",
    name: "Roca Rey",
    spriteSlug: "kings-rock",
    description: "Permite evolucionar a Poliwhirl y Slowpoke al intercambiar.",
    category: "evo",
    effect: { type: "evolve", method: "trade" },
    buyable: false,
    shopPrice: null,
  },
  "metal-coat": {
    id: "metal-coat",
    name: "Revestimiento Metálico",
    spriteSlug: "metal-coat",
    description:
      "Evoluciona a Scyther y Onix al intercambiar. Potencia ataques Acero.",
    category: "evo",
    effect: { type: "evolve", method: "trade" },
    buyable: false,
    shopPrice: null,
    condition: (state) =>
      hasPokemonOfType(state, "steel") ||
      hasPokemonWithName(state, ["Scyther", "Onix"]),
  },
  "dragon-scale": {
    id: "dragon-scale",
    name: "Escama Dragón",
    spriteSlug: "dragon-scale",
    description: "Evoluciona a Seadra al intercambiar.",
    category: "evo",
    effect: { type: "evolve", method: "trade" },
    buyable: false,
    shopPrice: null,
    condition: (state) => hasPokemonWithName(state, ["Horsea", "Seadra"]),
  },
  upgrade: {
    id: "upgrade",
    name: "Mejora",
    spriteSlug: "upgrade",
    description: "Evoluciona a Porygon al intercambiar.",
    category: "evo",
    effect: { type: "evolve", method: "trade" },
    buyable: false,
    shopPrice: null,
    condition: (state) => hasPokemonWithName(state, ["Porygon"]),
  },
  "dubious-disc": {
    id: "dubious-disc",
    name: "Disco Raro",
    spriteSlug: "dubious-disc",
    description: "Evoluciona a Porygon2 al intercambiar.",
    category: "evo",
    effect: { type: "evolve", method: "trade" },
    buyable: false,
    shopPrice: null,
    condition: (state) => hasPokemonWithName(state, ["Porygon2"]),
  },
  electirizer: {
    id: "electirizer",
    name: "Electrizador",
    spriteSlug: "electirizer",
    description: "Evoluciona a Electabuzz al intercambiar.",
    category: "evo",
    effect: { type: "evolve", method: "trade" },
    buyable: false,
    shopPrice: null,
    condition: (state) => hasPokemonWithName(state, ["Electabuzz"]),
  },
  magmarizer: {
    id: "magmarizer",
    name: "Magmarizador",
    spriteSlug: "magmarizer",
    description: "Evoluciona a Magmar al intercambiar.",
    category: "evo",
    effect: { type: "evolve", method: "trade" },
    buyable: false,
    shopPrice: null,
    condition: (state) => hasPokemonWithName(state, ["Magmar"]),
  },
  protector: {
    id: "protector",
    name: "Protector",
    spriteSlug: "protector",
    description: "Evoluciona a Rhydon al intercambiar.",
    category: "evo",
    effect: { type: "evolve", method: "trade" },
    buyable: false,
    shopPrice: null,
    condition: (state) => hasPokemonWithName(state, ["Rhydon"]),
  },
  "reaper-cloth": {
    id: "reaper-cloth",
    name: "Tela Parca",
    spriteSlug: "reaper-cloth",
    description: "Evoluciona a Dusclops al intercambiar.",
    category: "evo",
    effect: { type: "evolve", method: "trade" },
    buyable: false,
    shopPrice: null,
    condition: (state) => hasPokemonWithName(state, ["Dusclops"]),
  },
  "prism-scale": {
    id: "prism-scale",
    name: "Escama Prisma",
    spriteSlug: "prism-scale",
    description: "Evoluciona a Feebas al intercambiar.",
    category: "evo",
    effect: { type: "evolve", method: "trade" },
    buyable: false,
    shopPrice: null,
    condition: (state) => hasPokemonWithName(state, ["Feebas"]),
  },
  "whipped-dream": {
    id: "whipped-dream",
    name: "Nube Azucarada",
    spriteSlug: "whipped-dream",
    description: "Evoluciona a Swirlix al intercambiar.",
    category: "evo",
    effect: { type: "evolve", method: "trade" },
    buyable: false,
    shopPrice: null,
    condition: (state) => hasPokemonWithName(state, ["Swirlix"]),
  },
  sachet: {
    id: "sachet",
    name: "Saquito Perfumado",
    spriteSlug: "sachet",
    description: "Evoluciona a Spritzee al intercambiar.",
    category: "evo",
    effect: { type: "evolve", method: "trade" },
    buyable: false,
    shopPrice: null,
    condition: (state) => hasPokemonWithName(state, ["Spritzee"]),
  },
  "razor-claw": {
    id: "razor-claw",
    name: "Garra Afilada",
    spriteSlug: "razor-claw",
    description: "Evoluciona a Sneasel al subir de nivel de noche.",
    category: "evo",
    effect: { type: "evolve", method: "item" },
    buyable: false,
    shopPrice: null,
    condition: (state) => hasPokemonWithName(state, ["Sneasel"]),
  },
  "razor-fang": {
    id: "razor-fang",
    name: "Colmillo Filo",
    spriteSlug: "razor-fang",
    description: "Evoluciona a Gligar al subir de nivel de noche.",
    category: "evo",
    effect: { type: "evolve", method: "item" },
    buyable: false,
    shopPrice: null,
    condition: (state) => hasPokemonWithName(state, ["Gligar"]),
  },
  "choice-band": {
    id: "choice-band",
    name: "Cinta Elección",
    spriteSlug: "choice-band",
    description: "+50% Ataque. Solo permite usar un movimiento.",
    category: "held",
    effect: { type: "stat_boost", stat: "attack", amount: 1.5 },
    buyable: true,
    shopPrice: 5000,
  },
  "choice-scarf": {
    id: "choice-scarf",
    name: "Pañuelo Elección",
    spriteSlug: "choice-scarf",
    description: "+50% Velocidad. Solo permite usar un movimiento.",
    category: "held",
    effect: { type: "stat_boost", stat: "speed", amount: 1.5 },
    buyable: false,
    shopPrice: null,
  },
  "choice-specs": {
    id: "choice-specs",
    name: "Gafas Elección",
    spriteSlug: "choice-specs",
    description: "+50% Ataque Especial. Solo permite usar un movimiento.",
    category: "held",
    effect: { type: "stat_boost", stat: "spAtk", amount: 1.5 },
    buyable: false,
    shopPrice: null,
  },
  "life-orb": {
    id: "life-orb",
    name: "Vidasfera",
    spriteSlug: "life-orb",
    description: "+30% daño. El portador pierde 1/10 de sus PS cada turno.",
    category: "held",
    effect: { type: "stat_boost", stat: "attack", amount: 1.3 },
    buyable: true,
    shopPrice: 4000,
  },
  "focus-band": {
    id: "focus-band",
    name: "Banda Focus",
    spriteSlug: "focus-band",
    description:
      "10% de probabilidad de sobrevivir con 1 PS a un golpe fulminante.",
    category: "held",
    effect: { type: "passive" },
    buyable: true,
    shopPrice: 4000,
  },
  "focus-sash": {
    id: "focus-sash",
    name: "Faja Focus",
    spriteSlug: "focus-sash",
    description:
      "Sobrevive con 1 PS a un golpe que lo debilitaría si tiene PS completos. Se consume.",
    category: "held",
    effect: { type: "passive" },
    buyable: false,
    shopPrice: null,
  },
  "muscle-band": {
    id: "muscle-band",
    name: "Cinta Fuerte",
    spriteSlug: "muscle-band",
    description: "+10% poder en movimientos físicos.",
    category: "held",
    effect: { type: "stat_boost", stat: "attack", amount: 1.1 },
    buyable: true,
    shopPrice: 3000,
  },
  "wise-glasses": {
    id: "wise-glasses",
    name: "Gafas Especiales",
    spriteSlug: "wise-glasses",
    description: "+10% poder en movimientos especiales.",
    category: "held",
    effect: { type: "stat_boost", stat: "spAtk", amount: 1.1 },
    buyable: true,
    shopPrice: 3000,
  },
  "assault-vest": {
    id: "assault-vest",
    name: "Chaleco Asalto",
    spriteSlug: "assault-vest",
    description: "+50% Defensa Especial. Impide usar movimientos de estado.",
    category: "held",
    effect: { type: "stat_boost", stat: "spDef", amount: 1.5 },
    buyable: true,
    shopPrice: 3500,
  },
  eviolite: {
    id: "eviolite",
    name: "Mineral Evolutivo",
    spriteSlug: "eviolite",
    description:
      "+50% Defensa y Defensa Especial si el Pokémon puede evolucionar.",
    category: "held",
    effect: { type: "stat_boost", stat: "defense", amount: 1.5 },
    buyable: true,
    shopPrice: 3500,
  },
  "rocky-helmet": {
    id: "rocky-helmet",
    name: "Casco Dentado",
    spriteSlug: "rocky-helmet",
    description: "Devuelve 1/6 del daño a atacantes de contacto físico.",
    category: "held",
    effect: { type: "passive" },
    buyable: false,
    shopPrice: null,
  },
  "air-balloon": {
    id: "air-balloon",
    name: "Globo Aire",
    spriteSlug: "air-balloon",
    description:
      "Inmunidad a movimientos de tipo Tierra. Se pincha al recibir daño.",
    category: "held",
    effect: { type: "passive" },
    buyable: false,
    shopPrice: null,
  },
  "red-card": {
    id: "red-card",
    name: "Tarjeta Roja",
    spriteSlug: "red-card",
    description:
      "Fuerza al atacante a cambiar de Pokémon al recibir daño. Se consume.",
    category: "held",
    effect: { type: "passive" },
    buyable: false,
    shopPrice: null,
  },
  "eject-button": {
    id: "eject-button",
    name: "Botón Escape",
    spriteSlug: "eject-button",
    description:
      "El portador cambia automáticamente al recibir daño. Se consume.",
    category: "held",
    effect: { type: "passive" },
    buyable: false,
    shopPrice: null,
  },
  "shed-shell": {
    id: "shed-shell",
    name: "Caparazón Viejo",
    spriteSlug: "shed-shell",
    description: "Permite cambiar de Pokémon aunque el rival use retención.",
    category: "held",
    effect: { type: "passive" },
    buyable: false,
    shopPrice: null,
  },
  "white-herb": {
    id: "white-herb",
    name: "Hierba Blanca",
    spriteSlug: "white-herb",
    description: "Restaura estadísticas bajadas. Se consume al usarse.",
    category: "held",
    effect: { type: "passive" },
    buyable: false,
    shopPrice: null,
  },
  "mental-herb": {
    id: "mental-herb",
    name: "Hierba Mental",
    spriteSlug: "mental-herb",
    description: "Cura atracciones y bloqueos de movimiento. Se consume.",
    category: "held",
    effect: { type: "passive" },
    buyable: false,
    shopPrice: null,
  },
  "power-herb": {
    id: "power-herb",
    name: "Hierba Poder",
    spriteSlug: "power-herb",
    description: "Usa movimientos de carga en un turno. Se consume.",
    category: "held",
    effect: { type: "passive" },
    buyable: false,
    shopPrice: null,
  },
  "scope-lens": {
    id: "scope-lens",
    name: "Gafas Mira",
    spriteSlug: "scope-lens",
    description: "Aumenta la probabilidad de asestar golpes críticos.",
    category: "held",
    effect: { type: "passive" },
    buyable: false,
    shopPrice: null,
  },
  "razor-claw-held": {
    id: "razor-claw-held",
    name: "Garra Afilada (Sostenida)",
    spriteSlug: "razor-claw",
    description: "Aumenta la tasa de golpe crítico.",
    category: "held",
    effect: { type: "passive" },
    buyable: false,
    shopPrice: null,
  },
  "wide-lens": {
    id: "wide-lens",
    name: "Lente Amplia",
    spriteSlug: "wide-lens",
    description: "+10% de precisión en todos los movimientos.",
    category: "held",
    effect: { type: "passive" },
    buyable: false,
    shopPrice: null,
  },
  "zoom-lens": {
    id: "zoom-lens",
    name: "Lente Zoom",
    spriteSlug: "zoom-lens",
    description: "+20% precisión si el Pokémon actúa después del rival.",
    category: "held",
    effect: { type: "passive" },
    buyable: false,
    shopPrice: null,
  },
  "bright-powder": {
    id: "bright-powder",
    name: "Polvo Brillo",
    spriteSlug: "bright-powder",
    description: "Reduce la precisión de los ataques del rival en -10%.",
    category: "held",
    effect: { type: "passive" },
    buyable: false,
    shopPrice: null,
  },
  "quick-claw": {
    id: "quick-claw",
    name: "Garra Rápida",
    spriteSlug: "quick-claw",
    description:
      "20% de probabilidad de atacar primero sin importar la velocidad.",
    category: "held",
    effect: { type: "passive" },
    buyable: false,
    shopPrice: null,
  },
  "custap-berry": {
    id: "custap-berry",
    name: "Baya Custap",
    spriteSlug: "custap-berry",
    description:
      "Ataca primero una vez cuando los PS bajen al 25%. Se consume.",
    category: "berry",
    effect: { type: "passive" },
    buyable: false,
    shopPrice: null,
  },
  "lagging-tail": {
    id: "lagging-tail",
    name: "Cola Lenta",
    spriteSlug: "lagging-tail",
    description: "El portador siempre actúa al final del turno.",
    category: "held",
    effect: { type: "passive" },
    buyable: false,
    shopPrice: null,
  },
  "iron-ball": {
    id: "iron-ball",
    name: "Bola Acero",
    spriteSlug: "iron-ball",
    description:
      "Reduce la velocidad a la mitad y elimina la inmunidad Tierra de los flotadores.",
    category: "held",
    effect: { type: "stat_boost", stat: "speed", amount: 0.5 },
    buyable: false,
    shopPrice: null,
  },
  "macho-brace": {
    id: "macho-brace",
    name: "Arnés Fuerte",
    spriteSlug: "macho-brace",
    description: "Duplica los EVs ganados pero reduce la velocidad a la mitad.",
    category: "held",
    effect: { type: "passive" },
    buyable: false,
    shopPrice: null,
  },
  "lucky-egg": {
    id: "lucky-egg",
    name: "Huevo Suerte",
    spriteSlug: "lucky-egg",
    description: "El portador gana un 50% más de experiencia en combate.",
    category: "held",
    effect: { type: "xp_boost", multiplier: 1.5 },
    buyable: false,
    shopPrice: null,
  },
  "amulet-coin": {
    id: "amulet-coin",
    name: "Moneda Amuleto",
    spriteSlug: "amulet-coin",
    description: "Duplica los Pokédólares obtenidos en combate.",
    category: "held",
    effect: { type: "passive" },
    buyable: false,
    shopPrice: null,
  },
  "soothe-bell": {
    id: "soothe-bell",
    name: "Campana Suave",
    spriteSlug: "soothe-bell",
    description: "Aumenta la amistad del portador más rápidamente.",
    category: "held",
    effect: { type: "friendship_boost" },
    buyable: false,
    shopPrice: null,
  },
  "shell-bell": {
    id: "shell-bell",
    name: "Campana Concha",
    spriteSlug: "shell-bell",
    description: "Restaura 1/8 del daño infligido como PS.",
    category: "held",
    effect: { type: "passive" },
    buyable: false,
    shopPrice: null,
  },
  "black-sludge": {
    id: "black-sludge",
    name: "Barro Negro",
    spriteSlug: "black-sludge",
    description: "Restaura 1/16 de PS a Pokémon Veneno. Daña a los demás.",
    category: "held",
    effect: { type: "passive" },
    buyable: false,
    shopPrice: null,
  },
  "toxic-orb": {
    id: "toxic-orb",
    name: "Esfera Tóxica",
    spriteSlug: "toxic-orb",
    description: "Inflige envenenamiento grave al portador.",
    category: "held",
    effect: { type: "passive" },
    buyable: false,
    shopPrice: null,
  },
  "flame-orb": {
    id: "flame-orb",
    name: "Esfera Llama",
    spriteSlug: "flame-orb",
    description: "Quema al portador.",
    category: "held",
    effect: { type: "passive" },
    buyable: false,
    shopPrice: null,
  },
  "sticky-barb": {
    id: "sticky-barb",
    name: "Pincho Adherente",
    spriteSlug: "sticky-barb",
    description: "Daña al portador y se transfiere al atacar cuerpo a cuerpo.",
    category: "held",
    effect: { type: "passive" },
    buyable: false,
    shopPrice: null,
  },
  "big-root": {
    id: "big-root",
    name: "Raíz Grande",
    spriteSlug: "big-root",
    description: "Aumenta un 30% los PS absorbidos por movimientos drenantes.",
    category: "held",
    effect: { type: "passive" },
    buyable: false,
    shopPrice: null,
  },
  "binding-band": {
    id: "binding-band",
    name: "Venda Trampa",
    spriteSlug: "binding-band",
    description:
      "Los movimientos de trampa infligen 1/6 de daño en vez de 1/8.",
    category: "held",
    effect: { type: "passive" },
    buyable: false,
    shopPrice: null,
  },
  "safety-goggles": {
    id: "safety-goggles",
    name: "Gafas Protectoras",
    spriteSlug: "safety-goggles",
    description: "Inmunidad al clima dañino y al polvo/esporas.",
    category: "held",
    effect: { type: "passive" },
    buyable: false,
    shopPrice: null,
  },
  "terrain-extender": {
    id: "terrain-extender",
    name: "Amplificador Terreno",
    spriteSlug: "terrain-extender",
    description: "Extiende los terrenos creados por el portador a 8 turnos.",
    category: "held",
    effect: { type: "passive" },
    buyable: false,
    shopPrice: null,
  },
  "room-service": {
    id: "room-service",
    name: "Servicio Habitación",
    spriteSlug: "room-service",
    description: "Baja la Velocidad del portador al activarse Sala de Magia.",
    category: "held",
    effect: { type: "passive" },
    buyable: false,
    shopPrice: null,
  },
  "utility-umbrella": {
    id: "utility-umbrella",
    name: "Paraguas Multiuso",
    spriteSlug: "utility-umbrella",
    description: "El portador ignora los efectos del clima.",
    category: "held",
    effect: { type: "passive" },
    buyable: false,
    shopPrice: null,
  },

  // ── OBJETOS POTENCIADORES DE TIPO ──────────────────────────────────────────

  "twisted-spoon": {
    id: "twisted-spoon",
    name: "Cuchara Torcida",
    spriteSlug: "twisted-spoon",
    description: "+20% poder en ataques de tipo Psíquico.",
    category: "held",
    effect: { type: "stat_boost", stat: "spAtk", amount: 1.2 },
    buyable: false,
    shopPrice: null,
    condition: (state) => hasPokemonOfType(state, "psychic"),
  },
  charcoal: {
    id: "charcoal",
    name: "Carbón",
    spriteSlug: "charcoal",
    description: "+20% poder en ataques de tipo Fuego.",
    category: "held",
    effect: { type: "stat_boost", stat: "spAtk", amount: 1.2 },
    buyable: false,
    shopPrice: null,
    condition: (state) => hasPokemonOfType(state, "fire"),
  },
  "mystic-water": {
    id: "mystic-water",
    name: "Agua Mística",
    spriteSlug: "mystic-water",
    description: "+20% poder en ataques de tipo Agua.",
    category: "held",
    effect: { type: "stat_boost", stat: "spAtk", amount: 1.2 },
    buyable: false,
    shopPrice: null,
    condition: (state) => hasPokemonOfType(state, "water"),
  },
  "miracle-seed": {
    id: "miracle-seed",
    name: "Semilla Milagro",
    spriteSlug: "miracle-seed",
    description: "+20% poder en ataques de tipo Planta.",
    category: "held",
    effect: { type: "stat_boost", stat: "spAtk", amount: 1.2 },
    buyable: false,
    shopPrice: null,
    condition: (state) => hasPokemonOfType(state, "grass"),
  },
  magnet: {
    id: "magnet",
    name: "Imán",
    spriteSlug: "magnet",
    description: "+20% poder en ataques de tipo Eléctrico.",
    category: "held",
    effect: { type: "stat_boost", stat: "spAtk", amount: 1.2 },
    buyable: false,
    shopPrice: null,
    condition: (state) => hasPokemonOfType(state, "electric"),
  },
  "black-glasses": {
    id: "black-glasses",
    name: "Gafas de Sol",
    spriteSlug: "black-glasses",
    description: "+20% poder en ataques de tipo Siniestro.",
    category: "held",
    effect: { type: "stat_boost", stat: "attack", amount: 1.2 },
    buyable: false,
    shopPrice: null,
    condition: (state) => hasPokemonOfType(state, "dark"),
  },
  "black-belt": {
    id: "black-belt",
    name: "Cinturón Negro",
    spriteSlug: "black-belt",
    description: "+20% poder en ataques de tipo Lucha.",
    category: "held",
    effect: { type: "stat_boost", stat: "attack", amount: 1.2 },
    buyable: false,
    shopPrice: null,
    condition: (state) => hasPokemonOfType(state, "fighting"),
  },
  "dragon-fang": {
    id: "dragon-fang",
    name: "Colmillo Dragón",
    spriteSlug: "dragon-fang",
    description: "+20% poder en ataques de tipo Dragón.",
    category: "held",
    effect: { type: "stat_boost", stat: "attack", amount: 1.2 },
    buyable: false,
    shopPrice: null,
    condition: (state) => hasPokemonOfType(state, "dragon"),
  },
  "hard-stone": {
    id: "hard-stone",
    name: "Piedra Dura",
    spriteSlug: "hard-stone",
    description: "+20% poder en ataques de tipo Roca.",
    category: "held",
    effect: { type: "stat_boost", stat: "attack", amount: 1.2 },
    buyable: false,
    shopPrice: null,
    condition: (state) => hasPokemonOfType(state, "rock"),
  },
  "silver-powder": {
    id: "silver-powder",
    name: "Polvo Plata",
    spriteSlug: "silver-powder",
    description: "+20% poder en ataques de tipo Bicho.",
    category: "held",
    effect: { type: "stat_boost", stat: "attack", amount: 1.2 },
    buyable: false,
    shopPrice: null,
    condition: (state) => hasPokemonOfType(state, "bug"),
  },
  "poison-barb": {
    id: "poison-barb",
    name: "Flecha Venenosa",
    spriteSlug: "poison-barb",
    description: "+20% poder en ataques de tipo Veneno.",
    category: "held",
    effect: { type: "stat_boost", stat: "attack", amount: 1.2 },
    buyable: false,
    shopPrice: null,
    condition: (state) => hasPokemonOfType(state, "poison"),
  },
  "never-melt-ice": {
    id: "never-melt-ice",
    name: "Antiderretir",
    spriteSlug: "never-melt-ice",
    description: "+20% poder en ataques de tipo Hielo.",
    category: "held",
    effect: { type: "stat_boost", stat: "spAtk", amount: 1.2 },
    buyable: false,
    shopPrice: null,
    condition: (state) => hasPokemonOfType(state, "ice"),
  },
  "spell-tag": {
    id: "spell-tag",
    name: "Hechizo",
    spriteSlug: "spell-tag",
    description: "+20% poder en ataques de tipo Fantasma.",
    category: "held",
    effect: { type: "stat_boost", stat: "spAtk", amount: 1.2 },
    buyable: false,
    shopPrice: null,
    condition: (state) => hasPokemonOfType(state, "ghost"),
  },
  "soft-sand": {
    id: "soft-sand",
    name: "Arena Fina",
    spriteSlug: "soft-sand",
    description: "+20% poder en ataques de tipo Tierra.",
    category: "held",
    effect: { type: "stat_boost", stat: "attack", amount: 1.2 },
    buyable: false,
    shopPrice: null,
    condition: (state) => hasPokemonOfType(state, "ground"),
  },
  "sharp-beak": {
    id: "sharp-beak",
    name: "Pico Afilado",
    spriteSlug: "sharp-beak",
    description: "+20% poder en ataques de tipo Volador.",
    category: "held",
    effect: { type: "stat_boost", stat: "attack", amount: 1.2 },
    buyable: false,
    shopPrice: null,
    condition: (state) => hasPokemonOfType(state, "flying"),
  },
  "silk-scarf": {
    id: "silk-scarf",
    name: "Pañuelo Seda",
    spriteSlug: "silk-scarf",
    description: "+20% poder en ataques de tipo Normal.",
    category: "held",
    effect: { type: "stat_boost", stat: "attack", amount: 1.2 },
    buyable: false,
    shopPrice: null,
    condition: (state) => hasPokemonOfType(state, "normal"),
  },
  "fairy-feather": {
    id: "fairy-feather",
    name: "Pluma Hada",
    spriteSlug: "fairy-feather",
    description: "+20% poder en ataques de tipo Hada.",
    category: "held",
    effect: { type: "stat_boost", stat: "spAtk", amount: 1.2 },
    buyable: false,
    shopPrice: null,
    condition: (state) => hasPokemonOfType(state, "fairy"),
  },
  "punching-glove": {
    id: "punching-glove",
    name: "Guante de Boxeo",
    spriteSlug: "punching-glove",
    description: "+10% poder en movimientos de puñetazo. No hacen contacto.",
    category: "held",
    effect: { type: "stat_boost", stat: "attack", amount: 1.1 },
    buyable: false,
    shopPrice: null,
  },

  // ── OBJETOS PARA POKÉMON ESPECÍFICOS ──────────────────────────────────────

  "thick-club": {
    id: "thick-club",
    name: "Hueso Grueso",
    spriteSlug: "thick-club",
    description: "Duplica el Ataque de Cubone y Marowak.",
    category: "held",
    effect: { type: "stat_boost", stat: "attack", amount: 2.0 },
    buyable: false,
    shopPrice: null,
    condition: (state) =>
      hasPokemonWithName(state, ITEM_SPECIFIC_POKEMON.CUBONE),
  },
  "light-ball": {
    id: "light-ball",
    name: "Bolaluminosa",
    spriteSlug: "light-ball",
    description: "Duplica el Ataque y Ataque Especial de Pikachu.",
    category: "held",
    effect: { type: "stat_boost", stat: "spAtk", amount: 2.0 },
    buyable: false,
    shopPrice: null,
    condition: (state) =>
      hasPokemonWithName(state, ITEM_SPECIFIC_POKEMON.PIKACHU),
  },
  "deep-sea-tooth": {
    id: "deep-sea-tooth",
    name: "Diente Mar.",
    spriteSlug: "deep-sea-tooth",
    description: "Duplica el Ataque Especial de Clamperl.",
    category: "held",
    effect: { type: "stat_boost", stat: "spAtk", amount: 2.0 },
    buyable: false,
    shopPrice: null,
    condition: (state) =>
      hasPokemonWithName(state, ITEM_SPECIFIC_POKEMON.CLAMPERL),
  },
  "deep-sea-scale": {
    id: "deep-sea-scale",
    name: "Escama Mar.",
    spriteSlug: "deep-sea-scale",
    description: "Duplica la Defensa Especial de Clamperl.",
    category: "held",
    effect: { type: "stat_boost", stat: "spDef", amount: 2.0 },
    buyable: false,
    shopPrice: null,
    condition: (state) =>
      hasPokemonWithName(state, ITEM_SPECIFIC_POKEMON.CLAMPERL),
  },
  stick: {
    id: "stick",
    name: "Puerro",
    spriteSlug: "stick",
    description: "Aumenta la probabilidad de crítico de Farfetch'd.",
    category: "held",
    effect: { type: "stat_boost", stat: "attack", amount: 1.5 },
    buyable: false,
    shopPrice: null,
    condition: (state) =>
      hasPokemonWithName(state, ITEM_SPECIFIC_POKEMON.FARFETCHD),
  },
  "lucky-punch": {
    id: "lucky-punch",
    name: "Puño Suerte",
    spriteSlug: "lucky-punch",
    description: "Aumenta la probabilidad de crítico de Chansey.",
    category: "held",
    effect: { type: "passive" },
    buyable: false,
    shopPrice: null,
    condition: (state) =>
      hasPokemonWithName(state, ITEM_SPECIFIC_POKEMON.CHANSEY),
  },
  "metal-powder": {
    id: "metal-powder",
    name: "Polvo Metálico",
    spriteSlug: "metal-powder",
    description: "Aumenta la Defensa y Defensa Especial de Ditto.",
    category: "held",
    effect: { type: "stat_boost", stat: "defense", amount: 1.5 },
    buyable: false,
    shopPrice: null,
    condition: (state) =>
      hasPokemonWithName(state, ITEM_SPECIFIC_POKEMON.DITTO),
  },
  "quick-powder": {
    id: "quick-powder",
    name: "Polvo Rápido",
    spriteSlug: "quick-powder",
    description: "Duplica la Velocidad de Ditto.",
    category: "held",
    effect: { type: "stat_boost", stat: "speed", amount: 2.0 },
    buyable: false,
    shopPrice: null,
    condition: (state) =>
      hasPokemonWithName(state, ITEM_SPECIFIC_POKEMON.DITTO),
  },
  "soul-dew": {
    id: "soul-dew",
    name: "Rocío Bondad",
    spriteSlug: "soul-dew",
    description: "+20% Ataque Especial y Defensa Especial de Latias y Latios.",
    category: "held",
    effect: { type: "stat_boost", stat: "spAtk", amount: 1.2 },
    buyable: false,
    shopPrice: null,
    condition: (state) =>
      hasPokemonWithName(state, ITEM_SPECIFIC_POKEMON.LATIAS_LATIOS),
  },
  "adamant-orb": {
    id: "adamant-orb",
    name: "Diamansfera",
    spriteSlug: "adamant-orb",
    description:
      "+20% Ataque y Ataque Especial en movimientos Acero y Dragón de Dialga.",
    category: "held",
    effect: { type: "stat_boost", stat: "attack", amount: 1.2 },
    buyable: false,
    shopPrice: null,
    condition: (state) =>
      hasPokemonWithName(state, ITEM_SPECIFIC_POKEMON.DIALGA),
  },
  "lustrous-orb": {
    id: "lustrous-orb",
    name: "Lustresfera",
    spriteSlug: "lustrous-orb",
    description:
      "+20% Ataque y Ataque Especial en movimientos Agua y Dragón de Palkia.",
    category: "held",
    effect: { type: "stat_boost", stat: "spAtk", amount: 1.2 },
    buyable: false,
    shopPrice: null,
    condition: (state) =>
      hasPokemonWithName(state, ITEM_SPECIFIC_POKEMON.PALKIA),
  },
  "griseous-orb": {
    id: "griseous-orb",
    name: "Griseosfera",
    spriteSlug: "griseous-orb",
    description:
      "+20% Ataque y Ataque Especial en movimientos Fantasma y Dragón de Giratina.",
    category: "held",
    effect: { type: "stat_boost", stat: "attack", amount: 1.2 },
    buyable: false,
    shopPrice: null,
    condition: (state) =>
      hasPokemonWithName(state, ITEM_SPECIFIC_POKEMON.GIRATINA),
  },

  // ── INCIENSOS ──────────────────────────────────────────────────────────────

  "full-incense": {
    id: "full-incense",
    name: "Incienso Lleno",
    spriteSlug: "full-incense",
    description:
      "El portador siempre actúa al final del turno. Necesario para criar Snorlax→Munchlax.",
    category: "held",
    effect: { type: "passive" },
    buyable: false,
    shopPrice: null,
  },
  "lax-incense": {
    id: "lax-incense",
    name: "Incienso Relajado",
    spriteSlug: "lax-incense",
    description:
      "Reduce la precisión del rival. Necesario para criar Wobbuffet→Wynaut.",
    category: "held",
    effect: { type: "passive" },
    buyable: false,
    shopPrice: null,
  },
  "luck-incense": {
    id: "luck-incense",
    name: "Incienso Suerte",
    spriteSlug: "luck-incense",
    description:
      "Duplica Pokédólares en combate. Necesario para criar Chansey→Happiny.",
    category: "held",
    effect: { type: "passive" },
    buyable: false,
    shopPrice: null,
  },
  "pure-incense": {
    id: "pure-incense",
    name: "Incienso Puro",
    spriteSlug: "pure-incense",
    description:
      "Reduce la frecuencia de encuentros salvajes. Necesario para criar Chimecho→Chingling.",
    category: "held",
    effect: { type: "passive" },
    buyable: false,
    shopPrice: null,
  },
  "rock-incense": {
    id: "rock-incense",
    name: "Incienso Roca",
    spriteSlug: "rock-incense",
    description:
      "+20% poder en movimientos Roca. Necesario para criar Sudowoodo→Bonsly.",
    category: "held",
    effect: { type: "stat_boost", stat: "attack", amount: 1.2 },
    buyable: false,
    shopPrice: null,
  },
  "rose-incense": {
    id: "rose-incense",
    name: "Incienso Rosa",
    spriteSlug: "rose-incense",
    description:
      "+20% poder en movimientos Planta. Necesario para criar Roselia→Budew.",
    category: "held",
    effect: { type: "stat_boost", stat: "spAtk", amount: 1.2 },
    buyable: false,
    shopPrice: null,
  },
  "sea-incense": {
    id: "sea-incense",
    name: "Incienso Mar",
    spriteSlug: "sea-incense",
    description:
      "+20% poder en movimientos Agua. Necesario para criar Marill→Azurill.",
    category: "held",
    effect: { type: "stat_boost", stat: "spAtk", amount: 1.2 },
    buyable: false,
    shopPrice: null,
  },
  "wave-incense": {
    id: "wave-incense",
    name: "Incienso Ola",
    spriteSlug: "wave-incense",
    description:
      "+20% poder en movimientos Agua. Necesario para criar Mantine→Mantyke.",
    category: "held",
    effect: { type: "stat_boost", stat: "spAtk", amount: 1.2 },
    buyable: false,
    shopPrice: null,
  },
  "odd-incense": {
    id: "odd-incense",
    name: "Incienso Raro",
    spriteSlug: "odd-incense",
    description:
      "+20% poder en movimientos Psíquico. Necesario para criar Mr. Mime→Mime Jr.",
    category: "held",
    effect: { type: "stat_boost", stat: "spAtk", amount: 1.2 },
    buyable: false,
    shopPrice: null,
  },

  // ── MEGA STONES ────────────────────────────────────────────────────────────

  venusaurite: {
    id: "venusaurite",
    name: "Venusaurita",
    spriteSlug: "venusaurite",
    description: "Permite a Venusaur Megaevolucionar.",
    category: "held",
    effect: { type: "mega_evo", stoneId: "venusaurite" },
    buyable: false,
    shopPrice: null,
    condition: (state) => hasPokemonWithName(state, ["Venusaur"]),
  },
  charizardite_x: {
    id: "charizardite-x",
    name: "Charizardita X",
    spriteSlug: "charizardite-x",
    description: "Permite a Charizard Megaevolucionar a la forma X.",
    category: "held",
    effect: { type: "mega_evo", stoneId: "charizardite-x" },
    buyable: false,
    shopPrice: null,
    condition: (state) => hasPokemonWithName(state, ["Charizard"]),
  },
  "charizardite-y": {
    id: "charizardite-y",
    name: "Charizardita Y",
    spriteSlug: "charizardite-y",
    description: "Permite a Charizard Megaevolucionar a la forma Y.",
    category: "held",
    effect: { type: "mega_evo", stoneId: "charizardite-y" },
    buyable: false,
    shopPrice: null,
    condition: (state) => hasPokemonWithName(state, ["Charizard"]),
  },
  blastoisinite: {
    id: "blastoisinite",
    name: "Blastoisita",
    spriteSlug: "blastoisinite",
    description: "Permite a Blastoise Megaevolucionar.",
    category: "held",
    effect: { type: "mega_evo", stoneId: "blastoisinite" },
    buyable: false,
    shopPrice: null,
    condition: (state) => hasPokemonWithName(state, ["Blastoise"]),
  },
  beedrillite: {
    id: "beedrillite",
    name: "Beedrillita",
    spriteSlug: "beedrillite",
    description: "Permite a Beedrill Megaevolucionar.",
    category: "held",
    effect: { type: "mega_evo", stoneId: "beedrillite" },
    buyable: false,
    shopPrice: null,
    condition: (state) => hasPokemonWithName(state, ["Beedrill"]),
  },
  pidgeotite: {
    id: "pidgeotite",
    name: "Pidgeotita",
    spriteSlug: "pidgeotite",
    description: "Permite a Pidgeot Megaevolucionar.",
    category: "held",
    effect: { type: "mega_evo", stoneId: "pidgeotite" },
    buyable: false,
    shopPrice: null,
    condition: (state) => hasPokemonWithName(state, ["Pidgeot"]),
  },
  alakazite: {
    id: "alakazite",
    name: "Alakazita",
    spriteSlug: "alakazite",
    description: "Permite a Alakazam Megaevolucionar.",
    category: "held",
    effect: { type: "mega_evo", stoneId: "alakazite" },
    buyable: false,
    shopPrice: null,
    condition: (state) => hasPokemonWithName(state, ["Alakazam"]),
  },
  slowbronite: {
    id: "slowbronite",
    name: "Slowbronita",
    spriteSlug: "slowbronite",
    description: "Permite a Slowbro Megaevolucionar.",
    category: "held",
    effect: { type: "mega_evo", stoneId: "slowbronite" },
    buyable: false,
    shopPrice: null,
    condition: (state) => hasPokemonWithName(state, ["Slowbro"]),
  },
  gengarite: {
    id: "gengarite",
    name: "Gengarita",
    spriteSlug: "gengarite",
    description: "Permite a Gengar Megaevolucionar.",
    category: "held",
    effect: { type: "mega_evo", stoneId: "gengarite" },
    buyable: false,
    shopPrice: null,
    condition: (state) => hasPokemonWithName(state, ["Gengar"]),
  },
  kangaskhanite: {
    id: "kangaskhanite",
    name: "Kangaskhanita",
    spriteSlug: "kangaskhanite",
    description: "Permite a Kangaskhan Megaevolucionar.",
    category: "held",
    effect: { type: "mega_evo", stoneId: "kangaskhanite" },
    buyable: false,
    shopPrice: null,
    condition: (state) => hasPokemonWithName(state, ["Kangaskhan"]),
  },
  pinsirite: {
    id: "pinsirite",
    name: "Pinsirita",
    spriteSlug: "pinsirite",
    description: "Permite a Pinsir Megaevolucionar.",
    category: "held",
    effect: { type: "mega_evo", stoneId: "pinsirite" },
    buyable: false,
    shopPrice: null,
    condition: (state) => hasPokemonWithName(state, ["Pinsir"]),
  },
  gyaradosite: {
    id: "gyaradosite",
    name: "Gyaradosita",
    spriteSlug: "gyaradosite",
    description: "Permite a Gyarados Megaevolucionar.",
    category: "held",
    effect: { type: "mega_evo", stoneId: "gyaradosite" },
    buyable: false,
    shopPrice: null,
    condition: (state) => hasPokemonWithName(state, ["Gyarados"]),
  },
  aerodactylite: {
    id: "aerodactylite",
    name: "Aerodactylita",
    spriteSlug: "aerodactylite",
    description: "Permite a Aerodactyl Megaevolucionar.",
    category: "held",
    effect: { type: "mega_evo", stoneId: "aerodactylite" },
    buyable: false,
    shopPrice: null,
    condition: (state) => hasPokemonWithName(state, ["Aerodactyl"]),
  },
  mewtwonite_x: {
    id: "mewtwonite-x",
    name: "Mewtwonita X",
    spriteSlug: "mewtwonite-x",
    description: "Permite a Mewtwo Megaevolucionar a la forma X.",
    category: "held",
    effect: { type: "mega_evo", stoneId: "mewtwonite-x" },
    buyable: false,
    shopPrice: null,
    condition: (state) => hasPokemonWithName(state, ["Mewtwo"]),
  },
  "mewtwonite-y": {
    id: "mewtwonite-y",
    name: "Mewtwonita Y",
    spriteSlug: "mewtwonite-y",
    description: "Permite a Mewtwo Megaevolucionar a la forma Y.",
    category: "held",
    effect: { type: "mega_evo", stoneId: "mewtwonite-y" },
    buyable: false,
    shopPrice: null,
    condition: (state) => hasPokemonWithName(state, ["Mewtwo"]),
  },
  ampharosite: {
    id: "ampharosite",
    name: "Ampharosita",
    spriteSlug: "ampharosite",
    description: "Permite a Ampharos Megaevolucionar.",
    category: "held",
    effect: { type: "mega_evo", stoneId: "ampharosite" },
    buyable: false,
    shopPrice: null,
    condition: (state) => hasPokemonWithName(state, ["Ampharos"]),
  },
  steelixite: {
    id: "steelixite",
    name: "Steelixita",
    spriteSlug: "steelixite",
    description: "Permite a Steelix Megaevolucionar.",
    category: "held",
    effect: { type: "mega_evo", stoneId: "steelixite" },
    buyable: false,
    shopPrice: null,
    condition: (state) => hasPokemonWithName(state, ["Steelix"]),
  },
  scizorite: {
    id: "scizorite",
    name: "Scizorita",
    spriteSlug: "scizorite",
    description: "Permite a Scizor Megaevolucionar.",
    category: "held",
    effect: { type: "mega_evo", stoneId: "scizorite" },
    buyable: false,
    shopPrice: null,
    condition: (state) => hasPokemonWithName(state, ["Scizor"]),
  },
  heracronite: {
    id: "heracronite",
    name: "Heracronita",
    spriteSlug: "heracronite",
    description: "Permite a Heracross Megaevolucionar.",
    category: "held",
    effect: { type: "mega_evo", stoneId: "heracronite" },
    buyable: false,
    shopPrice: null,
    condition: (state) => hasPokemonWithName(state, ["Heracross"]),
  },
  houndoominite: {
    id: "houndoominite",
    name: "Houndoominita",
    spriteSlug: "houndoominite",
    description: "Permite a Houndoom Megaevolucionar.",
    category: "held",
    effect: { type: "mega_evo", stoneId: "houndoominite" },
    buyable: false,
    shopPrice: null,
    condition: (state) => hasPokemonWithName(state, ["Houndoom"]),
  },
  tyranitarite: {
    id: "tyranitarite",
    name: "Tyranitarita",
    spriteSlug: "tyranitarite",
    description: "Permite a Tyranitar Megaevolucionar.",
    category: "held",
    effect: { type: "mega_evo", stoneId: "tyranitarite" },
    buyable: false,
    shopPrice: null,
    condition: (state) => hasPokemonWithName(state, ["Tyranitar"]),
  },
  sceptilite: {
    id: "sceptilite",
    name: "Sceptilita",
    spriteSlug: "sceptilite",
    description: "Permite a Sceptile Megaevolucionar.",
    category: "held",
    effect: { type: "mega_evo", stoneId: "sceptilite" },
    buyable: false,
    shopPrice: null,
    condition: (state) => hasPokemonWithName(state, ["Sceptile"]),
  },
  blazikenite: {
    id: "blazikenite",
    name: "Blazikenita",
    spriteSlug: "blazikenite",
    description: "Permite a Blaziken Megaevolucionar.",
    category: "held",
    effect: { type: "mega_evo", stoneId: "blazikenite" },
    buyable: false,
    shopPrice: null,
    condition: (state) => hasPokemonWithName(state, ["Blaziken"]),
  },
  swampertite: {
    id: "swampertite",
    name: "Swampertita",
    spriteSlug: "swampertite",
    description: "Permite a Swampert Megaevolucionar.",
    category: "held",
    effect: { type: "mega_evo", stoneId: "swampertite" },
    buyable: false,
    shopPrice: null,
    condition: (state) => hasPokemonWithName(state, ["Swampert"]),
  },
  gardevoirite: {
    id: "gardevoirite",
    name: "Gardevoirita",
    spriteSlug: "gardevoirite",
    description: "Permite a Gardevoir Megaevolucionar.",
    category: "held",
    effect: { type: "mega_evo", stoneId: "gardevoirite" },
    buyable: false,
    shopPrice: null,
    condition: (state) => hasPokemonWithName(state, ["Gardevoir"]),
  },
  sablenite: {
    id: "sablenite",
    name: "Sablenita",
    spriteSlug: "sablenite",
    description: "Permite a Sableye Megaevolucionar.",
    category: "held",
    effect: { type: "mega_evo", stoneId: "sablenite" },
    buyable: false,
    shopPrice: null,
    condition: (state) => hasPokemonWithName(state, ["Sableye"]),
  },
  mawilite: {
    id: "mawilite",
    name: "Mawilita",
    spriteSlug: "mawilite",
    description: "Permite a Mawile Megaevolucionar.",
    category: "held",
    effect: { type: "mega_evo", stoneId: "mawilite" },
    buyable: false,
    shopPrice: null,
    condition: (state) => hasPokemonWithName(state, ["Mawile"]),
  },
  aggronite: {
    id: "aggronite",
    name: "Aggronita",
    spriteSlug: "aggronite",
    description: "Permite a Aggron Megaevolucionar.",
    category: "held",
    effect: { type: "mega_evo", stoneId: "aggronite" },
    buyable: false,
    shopPrice: null,
    condition: (state) => hasPokemonWithName(state, ["Aggron"]),
  },
  medichamite: {
    id: "medichamite",
    name: "Medichamita",
    spriteSlug: "medichamite",
    description: "Permite a Medicham Megaevolucionar.",
    category: "held",
    effect: { type: "mega_evo", stoneId: "medichamite" },
    buyable: false,
    shopPrice: null,
    condition: (state) => hasPokemonWithName(state, ["Medicham"]),
  },
  manectite: {
    id: "manectite",
    name: "Manectita",
    spriteSlug: "manectite",
    description: "Permite a Manectric Megaevolucionar.",
    category: "held",
    effect: { type: "mega_evo", stoneId: "manectite" },
    buyable: false,
    shopPrice: null,
    condition: (state) => hasPokemonWithName(state, ["Manectric"]),
  },
  sharpedonite: {
    id: "sharpedonite",
    name: "Sharpedonita",
    spriteSlug: "sharpedonite",
    description: "Permite a Sharpedo Megaevolucionar.",
    category: "held",
    effect: { type: "mega_evo", stoneId: "sharpedonite" },
    buyable: false,
    shopPrice: null,
    condition: (state) => hasPokemonWithName(state, ["Sharpedo"]),
  },
  cameruptite: {
    id: "cameruptite",
    name: "Cameruptita",
    spriteSlug: "cameruptite",
    description: "Permite a Camerupt Megaevolucionar.",
    category: "held",
    effect: { type: "mega_evo", stoneId: "cameruptite" },
    buyable: false,
    shopPrice: null,
    condition: (state) => hasPokemonWithName(state, ["Camerupt"]),
  },
  altarianite: {
    id: "altarianite",
    name: "Altarianita",
    spriteSlug: "altarianite",
    description: "Permite a Altaria Megaevolucionar.",
    category: "held",
    effect: { type: "mega_evo", stoneId: "altarianite" },
    buyable: false,
    shopPrice: null,
    condition: (state) => hasPokemonWithName(state, ["Altaria"]),
  },
  banettite: {
    id: "banettite",
    name: "Banettita",
    spriteSlug: "banettite",
    description: "Permite a Banette Megaevolucionar.",
    category: "held",
    effect: { type: "mega_evo", stoneId: "banettite" },
    buyable: false,
    shopPrice: null,
    condition: (state) => hasPokemonWithName(state, ["Banette"]),
  },
  absolite: {
    id: "absolite",
    name: "Absolita",
    spriteSlug: "absolite",
    description: "Permite a Absol Megaevolucionar.",
    category: "held",
    effect: { type: "mega_evo", stoneId: "absolite" },
    buyable: false,
    shopPrice: null,
    condition: (state) => hasPokemonWithName(state, ["Absol"]),
  },
  glalitite: {
    id: "glalitite",
    name: "Glalitita",
    spriteSlug: "glalitite",
    description: "Permite a Glalie Megaevolucionar.",
    category: "held",
    effect: { type: "mega_evo", stoneId: "glalitite" },
    buyable: false,
    shopPrice: null,
    condition: (state) => hasPokemonWithName(state, ["Glalie"]),
  },
  salamencite: {
    id: "salamencite",
    name: "Salamencita",
    spriteSlug: "salamencite",
    description: "Permite a Salamence Megaevolucionar.",
    category: "held",
    effect: { type: "mega_evo", stoneId: "salamencite" },
    buyable: false,
    shopPrice: null,
    condition: (state) => hasPokemonWithName(state, ["Salamence"]),
  },
  metagrossite: {
    id: "metagrossite",
    name: "Metagrossita",
    spriteSlug: "metagrossite",
    description: "Permite a Metagross Megaevolucionar.",
    category: "held",
    effect: { type: "mega_evo", stoneId: "metagrossite" },
    buyable: false,
    shopPrice: null,
    condition: (state) => hasPokemonWithName(state, ["Metagross"]),
  },
  latiasite: {
    id: "latiasite",
    name: "Latiasita",
    spriteSlug: "latiasite",
    description: "Permite a Latias Megaevolucionar.",
    category: "held",
    effect: { type: "mega_evo", stoneId: "latiasite" },
    buyable: false,
    shopPrice: null,
    condition: (state) => hasPokemonWithName(state, ["Latias"]),
  },
  latiosite: {
    id: "latiosite",
    name: "Latiosita",
    spriteSlug: "latiosite",
    description: "Permite a Latios Megaevolucionar.",
    category: "held",
    effect: { type: "mega_evo", stoneId: "latiosite" },
    buyable: false,
    shopPrice: null,
    condition: (state) => hasPokemonWithName(state, ["Latios"]),
  },
  lopunnite: {
    id: "lopunnite",
    name: "Lopunnita",
    spriteSlug: "lopunnite",
    description: "Permite a Lopunny Megaevolucionar.",
    category: "held",
    effect: { type: "mega_evo", stoneId: "lopunnite" },
    buyable: false,
    shopPrice: null,
    condition: (state) => hasPokemonWithName(state, ["Lopunny"]),
  },
  garchompite: {
    id: "garchompite",
    name: "Garchompita",
    spriteSlug: "garchompite",
    description: "Permite a Garchomp Megaevolucionar.",
    category: "held",
    effect: { type: "mega_evo", stoneId: "garchompite" },
    buyable: false,
    shopPrice: null,
    condition: (state) => hasPokemonWithName(state, ["Garchomp"]),
  },
  lucarionite: {
    id: "lucarionite",
    name: "Lucarionita",
    spriteSlug: "lucarionite",
    description: "Permite a Lucario Megaevolucionar.",
    category: "held",
    effect: { type: "mega_evo", stoneId: "lucarionite" },
    buyable: false,
    shopPrice: null,
    condition: (state) => hasPokemonWithName(state, ["Lucario"]),
  },
  abomasite: {
    id: "abomasite",
    name: "Abomasita",
    spriteSlug: "abomasite",
    description: "Permite a Abomasnow Megaevolucionar.",
    category: "held",
    effect: { type: "mega_evo", stoneId: "abomasite" },
    buyable: false,
    shopPrice: null,
    condition: (state) => hasPokemonWithName(state, ["Abomasnow"]),
  },
  galladite: {
    id: "galladite",
    name: "Galladita",
    spriteSlug: "galladite",
    description: "Permite a Gallade Megaevolucionar.",
    category: "held",
    effect: { type: "mega_evo", stoneId: "galladite" },
    buyable: false,
    shopPrice: null,
    condition: (state) => hasPokemonWithName(state, ["Gallade"]),
  },
  audinite: {
    id: "audinite",
    name: "Audinita",
    spriteSlug: "audinite",
    description: "Permite a Audino Megaevolucionar.",
    category: "held",
    effect: { type: "mega_evo", stoneId: "audinite" },
    buyable: false,
    shopPrice: null,
    condition: (state) => hasPokemonWithName(state, ["Audino"]),
  },
  diancite: {
    id: "diancite",
    name: "Diancita",
    spriteSlug: "diancite",
    description: "Permite a Diancie Megaevolucionar.",
    category: "held",
    effect: { type: "mega_evo", stoneId: "diancite" },
    buyable: false,
    shopPrice: null,
    condition: (state) => hasPokemonWithName(state, ["Diancie"]),
  },

  // ── BAYAS ─────────────────────────────────────────────────────────────────

  "oran-berry": {
    id: "oran-berry",
    name: "Baya Aranja",
    spriteSlug: "oran-berry",
    description: "Restaura 10 PS cuando los PS bajan.",
    category: "berry",
    effect: { type: "heal_hp", amount: 10 },
    buyable: true,
    shopPrice: 100,
  },
  "sitrus-berry": {
    id: "sitrus-berry",
    name: "Baya Zidra",
    spriteSlug: "sitrus-berry",
    description: "Restaura 25% de PS cuando bajan al 50%.",
    category: "berry",
    effect: { type: "heal_hp", amount: 0 },
    buyable: false,
    shopPrice: null,
  },
  "lum-berry": {
    id: "lum-berry",
    name: "Baya Ziuela",
    spriteSlug: "lum-berry",
    description: "Cura cualquier problema de estado. Se consume.",
    category: "berry",
    effect: { type: "heal_status" },
    buyable: false,
    shopPrice: null,
  },
  "leppa-berry": {
    id: "leppa-berry",
    name: "Baya Frambu",
    spriteSlug: "leppa-berry",
    description: "Restaura 10 PP de un movimiento cuando se agotan.",
    category: "berry",
    effect: { type: "pp_restore", amount: 10 },
    buyable: false,
    shopPrice: null,
  },
  "rawst-berry": {
    id: "rawst-berry",
    name: "Baya Rawst",
    spriteSlug: "rawst-berry",
    description: "Cura las quemaduras.",
    category: "berry",
    effect: { type: "heal_status" },
    buyable: false,
    shopPrice: null,
  },
  "aspear-berry": {
    id: "aspear-berry",
    name: "Baya Aspear",
    spriteSlug: "aspear-berry",
    description: "Descongela al portador.",
    category: "berry",
    effect: { type: "heal_status" },
    buyable: false,
    shopPrice: null,
  },
  "pecha-berry": {
    id: "pecha-berry",
    name: "Baya Pecha",
    spriteSlug: "pecha-berry",
    description: "Cura el envenenamiento.",
    category: "berry",
    effect: { type: "heal_status" },
    buyable: false,
    shopPrice: null,
  },
  "cheri-berry": {
    id: "cheri-berry",
    name: "Baya Cheri",
    spriteSlug: "cheri-berry",
    description: "Cura la parálisis.",
    category: "berry",
    effect: { type: "heal_status" },
    buyable: false,
    shopPrice: null,
  },
  "chesto-berry": {
    id: "chesto-berry",
    name: "Baya Chesto",
    spriteSlug: "chesto-berry",
    description: "Despierta al portador cuando se duerme.",
    category: "berry",
    effect: { type: "heal_status" },
    buyable: false,
    shopPrice: null,
  },
  "persim-berry": {
    id: "persim-berry",
    name: "Baya Persim",
    spriteSlug: "persim-berry",
    description: "Cura la confusión.",
    category: "berry",
    effect: { type: "heal_status" },
    buyable: false,
    shopPrice: null,
  },
  "aguav-berry": {
    id: "aguav-berry",
    name: "Baya Aguav",
    spriteSlug: "aguav-berry",
    description: "Restaura 1/3 de PS al 25% pero puede causar confusión.",
    category: "berry",
    effect: { type: "heal_hp", amount: 0 },
    buyable: false,
    shopPrice: null,
  },
  "figy-berry": {
    id: "figy-berry",
    name: "Baya Figy",
    spriteSlug: "figy-berry",
    description: "Restaura 1/3 de PS al 25% pero puede causar confusión.",
    category: "berry",
    effect: { type: "heal_hp", amount: 0 },
    buyable: false,
    shopPrice: null,
  },
  "iapapa-berry": {
    id: "iapapa-berry",
    name: "Baya Iapapa",
    spriteSlug: "iapapa-berry",
    description: "Restaura 1/3 de PS al 25% pero puede causar confusión.",
    category: "berry",
    effect: { type: "heal_hp", amount: 0 },
    buyable: false,
    shopPrice: null,
  },
  "mago-berry": {
    id: "mago-berry",
    name: "Baya Mago",
    spriteSlug: "mago-berry",
    description: "Restaura 1/3 de PS al 25% pero puede causar confusión.",
    category: "berry",
    effect: { type: "heal_hp", amount: 0 },
    buyable: false,
    shopPrice: null,
  },
  "wiki-berry": {
    id: "wiki-berry",
    name: "Baya Wiki",
    spriteSlug: "wiki-berry",
    description: "Restaura 1/3 de PS al 25% pero puede causar confusión.",
    category: "berry",
    effect: { type: "heal_hp", amount: 0 },
    buyable: false,
    shopPrice: null,
  },
  "salac-berry": {
    id: "salac-berry",
    name: "Baya Salac",
    spriteSlug: "salac-berry",
    description: "+1 Velocidad cuando los PS bajan al 25%.",
    category: "berry",
    effect: { type: "stat_boost", stat: "speed", amount: 1.5 },
    buyable: false,
    shopPrice: null,
  },
  "petaya-berry": {
    id: "petaya-berry",
    name: "Baya Petaya",
    spriteSlug: "petaya-berry",
    description: "+1 Ataque Especial cuando los PS bajan al 25%.",
    category: "berry",
    effect: { type: "stat_boost", stat: "spAtk", amount: 1.5 },
    buyable: false,
    shopPrice: null,
  },
  "apicot-berry": {
    id: "apicot-berry",
    name: "Baya Apicot",
    spriteSlug: "apicot-berry",
    description: "+1 Defensa Especial cuando los PS bajan al 25%.",
    category: "berry",
    effect: { type: "stat_boost", stat: "spDef", amount: 1.5 },
    buyable: false,
    shopPrice: null,
  },
  "lansat-berry": {
    id: "lansat-berry",
    name: "Baya Lansat",
    spriteSlug: "lansat-berry",
    description: "Aumenta la probabilidad de crítico al 25% de PS.",
    category: "berry",
    effect: { type: "passive" },
    buyable: false,
    shopPrice: null,
  },
  "liechi-berry": {
    id: "liechi-berry",
    name: "Baya Liechi",
    spriteSlug: "liechi-berry",
    description: "+1 Ataque cuando los PS bajan al 25%.",
    category: "berry",
    effect: { type: "stat_boost", stat: "attack", amount: 1.5 },
    buyable: false,
    shopPrice: null,
  },
  "ganlon-berry": {
    id: "ganlon-berry",
    name: "Baya Ganlon",
    spriteSlug: "ganlon-berry",
    description: "+1 Defensa cuando los PS bajan al 25%.",
    category: "berry",
    effect: { type: "stat_boost", stat: "defense", amount: 1.5 },
    buyable: false,
    shopPrice: null,
  },
  "starf-berry": {
    id: "starf-berry",
    name: "Baya Starf",
    spriteSlug: "starf-berry",
    description: "+2 en una estadística aleatoria al 25% de PS.",
    category: "berry",
    effect: { type: "passive" },
    buyable: false,
    shopPrice: null,
  },
  "enigma-berry": {
    id: "enigma-berry",
    name: "Baya Enigma",
    spriteSlug: "enigma-berry",
    description: "Restaura PS al recibir un golpe súper efectivo.",
    category: "berry",
    effect: { type: "heal_hp", amount: 0 },
    buyable: false,
    shopPrice: null,
  },
  "jaboca-berry": {
    id: "jaboca-berry",
    name: "Baya Jaboca",
    spriteSlug: "jaboca-berry",
    description: "Daña al rival si usa ataques físicos contra el portador.",
    category: "berry",
    effect: { type: "passive" },
    buyable: false,
    shopPrice: null,
  },
  "rowap-berry": {
    id: "rowap-berry",
    name: "Baya Rowap",
    spriteSlug: "rowap-berry",
    description: "Daña al rival si usa ataques especiales contra el portador.",
    category: "berry",
    effect: { type: "passive" },
    buyable: false,
    shopPrice: null,
  },
  "kee-berry": {
    id: "kee-berry",
    name: "Baya Kee",
    spriteSlug: "kee-berry",
    description: "+1 Defensa al recibir ataques físicos.",
    category: "berry",
    effect: { type: "stat_boost", stat: "defense", amount: 1.5 },
    buyable: false,
    shopPrice: null,
  },
  "maranga-berry": {
    id: "maranga-berry",
    name: "Baya Maranga",
    spriteSlug: "maranga-berry",
    description: "+1 Defensa Especial al recibir ataques especiales.",
    category: "berry",
    effect: { type: "stat_boost", stat: "spDef", amount: 1.5 },
    buyable: false,
    shopPrice: null,
  },
  "roseli-berry": {
    id: "roseli-berry",
    name: "Baya Roseli",
    spriteSlug: "roseli-berry",
    description: "Reduce el daño de un golpe Hada súper efectivo a la mitad.",
    category: "berry",
    effect: { type: "passive" },
    buyable: false,
    shopPrice: null,
  },
  "occa-berry": {
    id: "occa-berry",
    name: "Baya Occa",
    spriteSlug: "occa-berry",
    description: "Reduce el daño de un golpe Fuego súper efectivo a la mitad.",
    category: "berry",
    effect: { type: "passive" },
    buyable: false,
    shopPrice: null,
  },
  "passho-berry": {
    id: "passho-berry",
    name: "Baya Passho",
    spriteSlug: "passho-berry",
    description: "Reduce el daño de un golpe Agua súper efectivo a la mitad.",
    category: "berry",
    effect: { type: "passive" },
    buyable: false,
    shopPrice: null,
  },
  "wacan-berry": {
    id: "wacan-berry",
    name: "Baya Wacan",
    spriteSlug: "wacan-berry",
    description:
      "Reduce el daño de un golpe Eléctrico súper efectivo a la mitad.",
    category: "berry",
    effect: { type: "passive" },
    buyable: false,
    shopPrice: null,
  },
  "rindo-berry": {
    id: "rindo-berry",
    name: "Baya Rindo",
    spriteSlug: "rindo-berry",
    description: "Reduce el daño de un golpe Planta súper efectivo a la mitad.",
    category: "berry",
    effect: { type: "passive" },
    buyable: false,
    shopPrice: null,
  },
  "yache-berry": {
    id: "yache-berry",
    name: "Baya Yache",
    spriteSlug: "yache-berry",
    description: "Reduce el daño de un golpe Hielo súper efectivo a la mitad.",
    category: "berry",
    effect: { type: "passive" },
    buyable: false,
    shopPrice: null,
  },
  "chople-berry": {
    id: "chople-berry",
    name: "Baya Chople",
    spriteSlug: "chople-berry",
    description: "Reduce el daño de un golpe Lucha súper efectivo a la mitad.",
    category: "berry",
    effect: { type: "passive" },
    buyable: false,
    shopPrice: null,
  },
  "kebia-berry": {
    id: "kebia-berry",
    name: "Baya Kebia",
    spriteSlug: "kebia-berry",
    description: "Reduce el daño de un golpe Veneno súper efectivo a la mitad.",
    category: "berry",
    effect: { type: "passive" },
    buyable: false,
    shopPrice: null,
  },
  "shuca-berry": {
    id: "shuca-berry",
    name: "Baya Shuca",
    spriteSlug: "shuca-berry",
    description: "Reduce el daño de un golpe Tierra súper efectivo a la mitad.",
    category: "berry",
    effect: { type: "passive" },
    buyable: false,
    shopPrice: null,
  },
  "coba-berry": {
    id: "coba-berry",
    name: "Baya Coba",
    spriteSlug: "coba-berry",
    description:
      "Reduce el daño de un golpe Volador súper efectivo a la mitad.",
    category: "berry",
    effect: { type: "passive" },
    buyable: false,
    shopPrice: null,
  },
  "payapa-berry": {
    id: "payapa-berry",
    name: "Baya Payapa",
    spriteSlug: "payapa-berry",
    description:
      "Reduce el daño de un golpe Psíquico súper efectivo a la mitad.",
    category: "berry",
    effect: { type: "passive" },
    buyable: false,
    shopPrice: null,
  },
  "tanga-berry": {
    id: "tanga-berry",
    name: "Baya Tanga",
    spriteSlug: "tanga-berry",
    description: "Reduce el daño de un golpe Bicho súper efectivo a la mitad.",
    category: "berry",
    effect: { type: "passive" },
    buyable: false,
    shopPrice: null,
  },
  "charti-berry": {
    id: "charti-berry",
    name: "Baya Charti",
    spriteSlug: "charti-berry",
    description: "Reduce el daño de un golpe Roca súper efectivo a la mitad.",
    category: "berry",
    effect: { type: "passive" },
    buyable: false,
    shopPrice: null,
  },
  "kasib-berry": {
    id: "kasib-berry",
    name: "Baya Kasib",
    spriteSlug: "kasib-berry",
    description:
      "Reduce el daño de un golpe Fantasma súper efectivo a la mitad.",
    category: "berry",
    effect: { type: "passive" },
    buyable: false,
    shopPrice: null,
  },
  "haban-berry": {
    id: "haban-berry",
    name: "Baya Haban",
    spriteSlug: "haban-berry",
    description: "Reduce el daño de un golpe Dragón súper efectivo a la mitad.",
    category: "berry",
    effect: { type: "passive" },
    buyable: false,
    shopPrice: null,
  },
  "colbur-berry": {
    id: "colbur-berry",
    name: "Baya Colbur",
    spriteSlug: "colbur-berry",
    description:
      "Reduce el daño de un golpe Siniestro súper efectivo a la mitad.",
    category: "berry",
    effect: { type: "passive" },
    buyable: false,
    shopPrice: null,
  },
  "babiri-berry": {
    id: "babiri-berry",
    name: "Baya Babiri",
    spriteSlug: "babiri-berry",
    description: "Reduce el daño de un golpe Acero súper efectivo a la mitad.",
    category: "berry",
    effect: { type: "passive" },
    buyable: false,
    shopPrice: null,
  },
  "chilan-berry": {
    id: "chilan-berry",
    name: "Baya Chilan",
    spriteSlug: "chilan-berry",
    description: "Reduce el daño de un golpe Normal a la mitad.",
    category: "berry",
    effect: { type: "passive" },
    buyable: false,
    shopPrice: null,
  },

  // ── ESPECIALES / HISTORIA ──────────────────────────────────────────────────

  "exp-share": {
    id: "exp-share",
    name: "Repartir Exp.",
    spriteSlug: "exp-share",
    description: "El equipo comparte la experiencia ganada en combate.",
    category: "special",
    effect: { type: "xp_boost", multiplier: 1.0 },
    buyable: false,
    shopPrice: null,
  },
  "mega-bracelet": {
    id: "mega-bracelet",
    name: "Mega-Brazalete",
    spriteSlug: "mega-bracelet",
    description: "Permite usar la Megaevolución en combate.",
    category: "special",
    effect: { type: "passive" },
    buyable: false,
    shopPrice: null,
    condition: (state) => hasMegaEvolutionCandidate(state),
  },
  "cable-link": {
    id: "cable-link",
    name: "Cable Link",
    spriteSlug: "link-cable",
    description: "Evoluciona a Pokémon que requieren intercambio.",
    category: "evo",
    effect: { type: "evolve", method: "trade" },
    buyable: true,
    shopPrice: 2000,
  },
  "carta-bosque": {
    id: "carta-bosque",
    name: "Carta Bosque",
    spriteSlug: "data-card-01",
    description: "+20% experiencia ganada.",
    category: "special",
    effect: { type: "xp_boost", multiplier: 1.2 },
    buyable: false,
    shopPrice: null,
  },
  "carta-cueva": {
    id: "carta-cueva",
    name: "Carta Cueva",
    spriteSlug: "data-card-02",
    description: "+20% experiencia ganada.",
    category: "special",
    effect: { type: "xp_boost", multiplier: 1.2 },
    buyable: false,
    shopPrice: null,
  },
  "carta-monte": {
    id: "carta-monte",
    name: "Carta Monte",
    spriteSlug: "data-card-03",
    description: "+20% experiencia ganada.",
    category: "special",
    effect: { type: "xp_boost", multiplier: 1.2 },
    buyable: false,
    shopPrice: null,
  },
  "carta-mar": {
    id: "carta-mar",
    name: "Carta Mar",
    spriteSlug: "data-card-04",
    description: "+20% experiencia ganada.",
    category: "special",
    effect: { type: "xp_boost", multiplier: 1.2 },
    buyable: false,
    shopPrice: null,
  },
  "carta-ciudad": {
    id: "carta-ciudad",
    name: "Carta Ciudad",
    spriteSlug: "data-card-05",
    description: "+20% experiencia ganada.",
    category: "special",
    effect: { type: "xp_boost", multiplier: 1.2 },
    buyable: false,
    shopPrice: null,
  },
};

// ─────────────────────────────────────────────────────────────────────────────

export function generateLootOptions(
  excludeCategories: ItemCategory[] = [],
  gameState?: { team: any[]; pc: any[] },
): string[] {
  const buyables = Object.values(ITEMS)
    .filter((item) => {
      const isValidCategory = !excludeCategories.includes(item.category);
      if (!item.buyable || !isValidCategory) return false;
      if (item.condition && gameState) {
        return item.condition(gameState);
      }
      return !item.condition;
    })
    .map((item) => item.id);

  const shuffled = buyables.sort(() => 0.5 - Math.random());
  return shuffled.slice(0, 3);
}
